/*  MAIN ACTIONS   */
export const FIRST_TIME_LOGIN = 'FIRST_TIME_LOGIN';
export const SET_LANGUAGE = 'SET_LANGUAGE';
export const GET_USER_AGENT = 'GET_USER_AGENT';
export const TRIGGER_SAVINGS_PAGE = 'TRIGGER_SAVINGS_PAGE';
export const GET_USER_AVATAR_SOURCE = 'GET_USER_AVATAR_SOURCE';
export const GET_CAPTURED_IMAGE_URI = 'GET_CAPTURED_IMAGE_URI';



