/*  MAIN ACTIONS   */
export const SET_FIRST_TIME_LOGIN = 'SET_FIRST_TIME_LOGIN';
export const USER = 'USER';
export const SET_SPLASH_VISIBLE = 'SET_SPLASH_VISIBLE';
export const SET_TASKS = 'SET_TASKS';
export const SET_CHALLENGES  = 'SET_CHALLENGES';
